# render.yaml
services:
  - type: web
    name: ietr-webshield
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ietr_site.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: ietr-db
          property: connectionString
      - key: PYTHON_VERSION
        value: "3.11.0"

databases:
  - name: ietr-db
    databaseName: ietr_webshield
    user: ietr_user
    plan: free